### ISSUE TITLE
Consolidate Tables and Views for Chain Interaction

### ISSUE THREAD

**Issue by saberistic** [designitycom/web-services#100]
### Description
Based on the recent discussion, the decision has been made to consolidate all tables and views accessed by the service for chain interaction. This will enhance efficiency and streamline data access for improved performance.

### Tasks
The following workflows need to be migrated to achieve this consolidation:

- [ ] **Login Workflow**
  - **Current Base:** `Creatives Master`
  - **Target Base:** `Smart Contacts`

- [ ] **Processing Scores Workflow**
  - **Current Base:** `growth`
  - **Target Base:** Smart Contacts for Devs

### Steps to Reproduce
- [ ] Trigger login worklow
- [ ] Trigger processing scores workflow

### Expected Behavior
After the migration, we expect new and current users update and read values from new base
